"""Point-in-time, walk-forward backtest -> PWA-compatible /backtest JSON.

Design
------
* Signals are generated by the SAME ``screen_universe(as_of=...)`` the live app
  uses, so backtested entries match what the Screener tab would have shown on
  that date. No separate, drifting signal logic.
* Entry is at the NEXT session's open after a signal (no look-ahead).
* Exits are a fixed, deterministic model: percentage stop, percentage target,
  and a time stop. The stop is assumed to fill at the stop price -- optimistic
  on thin counters, which is called out in the published ``note``.
* Train/test is a chronological split (default 70/30) on ENTRY date. The test
  half is genuinely out-of-sample: nothing here is optimised against it.
* For CI tractability the engine caps the universe to the most liquid names and
  rebalances on a fixed session stride. Both are env-tunable knobs; widen them
  when you want a heavier, slower run.

This is a clean-room reconstruction of the backtest that did not survive the
repo migration. Reconcile its numbers against your prior engine before trusting
them; the exit model here is param-driven, not the structural stop the live
screener suggests.
"""
from __future__ import annotations

import argparse
import json
import math
import os
import statistics
from bisect import bisect_right
from dataclasses import dataclass
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

import data_fetcher
from bmk_screener_v3 import STRATEGIES, ScreenerConfig, enrich, screen_universe
from export_scan import (
    OUT,
    _fetch_benchmark,
    _metadata,
    publish_files,
)

# ----------------------------------------------------------------- parameters
SPLIT = float(os.environ.get("BT_SPLIT", "0.70"))            # train fraction
LOOKBACK_YEARS = float(os.environ.get("BT_LOOKBACK_YEARS", "1.6"))
STEP_DAYS = int(os.environ.get("BT_STEP_DAYS", "5"))          # rebalance stride
MAX_SYMBOLS = int(os.environ.get("BT_MAX_SYMBOLS", "300"))    # liquidity cap
STOP_LOSS_PCT = float(os.environ.get("BT_STOP_LOSS_PCT", "8"))
TAKE_PROFIT_PCT = float(os.environ.get("BT_TAKE_PROFIT_PCT", "20"))
HOLD_DAYS = int(os.environ.get("BT_HOLD_DAYS", "25"))
COMMISSION_PCT = float(os.environ.get("BT_COMMISSION_PCT", "0.15"))  # per side
MIN_HISTORY = int(os.environ.get("BT_MIN_HISTORY", "300"))
EQUITY_POINTS = 60
MAX_TEST_TRADES_PUBLISHED = 250

PARAMS = {
    "stop_loss_pct": STOP_LOSS_PCT,
    "take_profit_pct": TAKE_PROFIT_PCT,
    "hold_days": HOLD_DAYS,
    "commission_pct": COMMISSION_PCT,
}


@dataclass
class Trade:
    strategy: str
    symbol: str
    entry_date: pd.Timestamp
    exit_date: pd.Timestamp
    ret_pct: float          # net of commission, both sides
    hold_days: int
    phase: str              # "train" | "test"


def _round(value: float, digits: int = 2) -> float | None:
    if value is None or not math.isfinite(value):
        return None
    return round(float(value), digits)


def _liquidity_rank(prices: dict[str, pd.DataFrame]) -> list[str]:
    """Rank symbols by median 20-session traded value; cap to MAX_SYMBOLS."""
    scored: list[tuple[float, str]] = []
    for symbol, frame in prices.items():
        try:
            tv = (frame["close"] * frame["volume"]).tail(20)
            median = float(tv.median()) if len(tv) else 0.0
        except Exception:
            median = 0.0
        if math.isfinite(median) and median > 0:
            scored.append((median, symbol))
    scored.sort(reverse=True)
    return [symbol for _, symbol in scored[:MAX_SYMBOLS]]


def _rebalance_dates(benchmark: pd.DataFrame) -> list[pd.Timestamp]:
    """Sessions on which we screen, spaced STEP_DAYS apart, warm-up respected."""
    idx = enrich(benchmark).index
    if len(idx) <= MIN_HISTORY + 2:
        return []
    window = int(LOOKBACK_YEARS * 252)
    start = max(MIN_HISTORY, len(idx) - window)
    # Leave a one-session tail so every signal has a next bar to enter on.
    return list(idx[start:-1:STEP_DAYS])


def _simulate_exit(
    future: pd.DataFrame, entry_price: float
) -> tuple[pd.Timestamp, float, int]:
    """Walk bars after entry; return (exit_date, gross_ret_pct, hold_sessions)."""
    stop = entry_price * (1 - STOP_LOSS_PCT / 100.0)
    target = entry_price * (1 + TAKE_PROFIT_PCT / 100.0)
    held = 0
    for ts, bar in future.iterrows():
        held += 1
        low, high, close = float(bar["low"]), float(bar["high"]), float(bar["close"])
        # Stop takes priority over target within the same bar (conservative).
        if low <= stop:
            return ts, (stop / entry_price - 1) * 100.0, held
        if high >= target:
            return ts, (target / entry_price - 1) * 100.0, held
        if held >= HOLD_DAYS:
            return ts, (close / entry_price - 1) * 100.0, held
    # Ran out of data: mark to last available close.
    ts = future.index[-1]
    return ts, (float(future["close"].iloc[-1]) / entry_price - 1) * 100.0, held


def _run_backtest(
    prices: dict[str, pd.DataFrame],
    benchmark: pd.DataFrame,
    metadata: dict[str, dict[str, str]],
) -> tuple[list[Trade], pd.Timestamp, pd.Timestamp]:
    cfg = ScreenerConfig()
    dates = _rebalance_dates(benchmark)
    if not dates:
        raise RuntimeError("insufficient benchmark history for a backtest window")
    split_date = dates[max(0, int(len(dates) * SPLIT) - 1)]

    # One concurrent position per (symbol, strategy). Value is the exit date we
    # are blocked until.
    blocked_until: dict[tuple[str, str], pd.Timestamp] = {}
    trades: list[Trade] = []
    commission = COMMISSION_PCT * 2.0  # round trip

    for as_of in dates:
        candidates = screen_universe(prices, benchmark, metadata, cfg, as_of=as_of)
        for cand in candidates:
            if str(cand.get("status", "ACTIVE")).upper() != "ACTIVE":
                continue  # WATCH candidates are unconfirmed; don't trade them
            symbol, strategy = str(cand["symbol"]), str(cand["strategy"])
            key = (symbol, strategy)
            if key in blocked_until and as_of <= blocked_until[key]:
                continue
            frame = prices.get(cand.get("yahoo_symbol", symbol))
            if frame is None:
                frame = prices.get(symbol)
            if frame is None:
                continue
            future = frame.loc[frame.index > as_of]
            if len(future) < 2:
                continue
            entry_bar = future.iloc[0]
            entry_date = future.index[0]
            entry_price = float(entry_bar["open"])
            if not math.isfinite(entry_price) or entry_price <= 0:
                continue
            exit_date, gross, held = _simulate_exit(future.iloc[1:], entry_price)
            net = gross - commission
            trades.append(Trade(
                strategy=strategy, symbol=symbol,
                entry_date=entry_date, exit_date=exit_date,
                ret_pct=net, hold_days=held,
                phase="train" if entry_date <= split_date else "test",
            ))
            blocked_until[key] = exit_date

    return trades, dates[0], dates[-1]


def _phase_stats(trades: list[Trade]) -> dict[str, Any]:
    if not trades:
        return {"trades": 0, "win_rate": None, "avg": None, "median": None,
                "profit_factor": None, "best": None, "worst": None, "avg_hold": None}
    rets = [t.ret_pct for t in trades]
    wins = [r for r in rets if r > 0]
    gains = sum(wins)
    losses = -sum(r for r in rets if r <= 0)
    pf = gains / losses if losses > 0 else (float("inf") if gains > 0 else 0.0)
    return {
        "trades": len(trades),
        "win_rate": _round(100.0 * len(wins) / len(rets), 1),
        "avg": _round(statistics.fmean(rets)),
        "median": _round(statistics.median(rets)),
        "profit_factor": _round(pf) if math.isfinite(pf) else 99.0,
        "best": _round(max(rets)),
        "worst": _round(min(rets)),
        "avg_hold": _round(statistics.fmean(t.hold_days for t in trades), 1),
    }


def _equity_curve(trades: list[Trade]) -> list[dict[str, Any]]:
    """Compounded equity (base 100), ordered by exit date, downsampled."""
    ordered = sorted(trades, key=lambda t: t.exit_date)
    value = 100.0
    curve: list[dict[str, Any]] = []
    for t in ordered:
        value *= 1 + t.ret_pct / 100.0
        curve.append({"d": t.exit_date.date().isoformat(), "v": round(value, 2)})
    if len(curve) <= EQUITY_POINTS:
        return curve
    step = len(curve) / EQUITY_POINTS
    sampled = [curve[min(len(curve) - 1, int(i * step))] for i in range(EQUITY_POINTS)]
    sampled[-1] = curve[-1]
    return sampled


def _max_drawdown(curve: list[dict[str, Any]]) -> float | None:
    if not curve:
        return None
    peak = curve[0]["v"]
    worst = 0.0
    for point in curve:
        peak = max(peak, point["v"])
        worst = min(worst, point["v"] / peak - 1.0)
    return _round(worst * 100.0)


def _verdict(train: dict[str, Any], test: dict[str, Any]) -> dict[str, str]:
    n = test["trades"] or 0
    if n < 20:
        return {"level": "thin",
                "text": f"Only {n} out-of-sample trades. Not enough to judge."}
    tpf = test["profit_factor"] or 0.0
    trpf = train["profit_factor"] or 0.0
    if tpf < 1.0:
        return {"level": "bad",
                "text": "Loses money out of sample. Entry criteria, not exits, are the suspect."}
    if tpf >= 1.5 and tpf >= 0.75 * trpf:
        return {"level": "good",
                "text": "Edge holds out of sample with acceptable decay from train."}
    return {"level": "warn",
            "text": "Test decays from train. Edge is real but weaker out of sample."}


def _strategy_block(strategy: str, trades: list[Trade]) -> dict[str, Any]:
    train = [t for t in trades if t.phase == "train"]
    test = [t for t in trades if t.phase == "test"]
    train_stats, test_stats = _phase_stats(train), _phase_stats(test)
    test_curve = _equity_curve(test)
    published_test = sorted(test, key=lambda t: t.exit_date, reverse=True)[:MAX_TEST_TRADES_PUBLISHED]
    trade_rows = [
        {"p": "test", "s": t.symbol,
         "in": t.entry_date.date().isoformat(),
         "out": t.exit_date.date().isoformat(),
         "r": _round(t.ret_pct)}
        for t in sorted(published_test, key=lambda t: t.exit_date, reverse=True)
    ]
    return {
        "strategy": strategy,
        "train": train_stats,
        "test": test_stats,
        "verdict": _verdict(train_stats, test_stats),
        "equity": {"train": _equity_curve(train), "test": test_curve},
        "max_drawdown": _max_drawdown(test_curve),
        "trades_total": len(trades),
        "trades": trade_rows,
    }


def run(do_publish: bool = False) -> dict[str, Any]:
    prices_all = data_fetcher.fetch_market()
    keep = set(_liquidity_rank(prices_all))
    prices = {s: f for s, f in prices_all.items() if s in keep}
    benchmark = _fetch_benchmark()
    metadata = _metadata()

    trades, first_date, last_date = _run_backtest(prices, benchmark, metadata)
    by_strategy: dict[str, list[Trade]] = {s: [] for s in STRATEGIES}
    for t in trades:
        by_strategy.setdefault(t.strategy, []).append(t)

    strategies = [_strategy_block(s, by_strategy.get(s, [])) for s in STRATEGIES]
    now = datetime.now(timezone.utc)
    payload = {
        "generated_at": now.isoformat(),
        "market": "MYX",
        "currency": "RM",
        "universe_size": len(prices),
        "split": SPLIT,
        "date_from": first_date.date().isoformat(),
        "date_to": last_date.date().isoformat(),
        "params": PARAMS,
        "strategy_config": {s: dict(PARAMS) for s in STRATEGIES},
        "strategies": strategies,
        "note": ("Point-in-time walk-forward. Entry at next bar's open; stop "
                 "assumed to fill at the stop price. Real fills on thin counters "
                 "will be worse. Reconstructed engine — reconcile before trusting. "
                 "Not advice."),
    }
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "backtest.json").write_text(
        json.dumps(payload, separators=(",", ":")), encoding="utf-8")
    if do_publish:
        publish_files(only=("backtest",))
    total = sum(len(v) for v in by_strategy.values())
    print(f"Backtest: {total} trades across {len(prices)} names, "
          f"{first_date.date()} -> {last_date.date()}")
    return payload


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--publish", action="store_true")
    run(parser.parse_args().publish)
